#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
# Using build pattern: R
# autospec version: v2
# autospec commit: 250a666
#
Name     : R-utf8
Version  : 1.2.4
Release  : 54
URL      : https://cran.r-project.org/src/contrib/utf8_1.2.4.tar.gz
Source0  : https://cran.r-project.org/src/contrib/utf8_1.2.4.tar.gz
Summary  : Unicode Text Processing
Group    : Development/Tools
License  : Apache-2.0 ICU
Requires: R-utf8-lib = %{version}-%{release}
Requires: R-utf8-license = %{version}-%{release}
BuildRequires : buildreq-R

%description
text (Unicode). Input, validate, normalize, encode, format, and
    display.

%package lib
Summary: lib components for the R-utf8 package.
Group: Libraries
Requires: R-utf8-license = %{version}-%{release}

%description lib
lib components for the R-utf8 package.


%package license
Summary: license components for the R-utf8 package.
Group: Default

%description license
license components for the R-utf8 package.


%prep
%setup -q -n utf8
pushd ..
cp -a utf8 buildavx2
popd

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1698074331

%install
export SOURCE_DATE_EPOCH=1698074331
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/R-utf8
cp %{_builddir}/utf8/LICENSE %{buildroot}/usr/share/package-licenses/R-utf8/2b8b815229aa8a61e483fb4ba0588b8b6c491890 || :
cp %{_builddir}/utf8/src/utf8lite/LICENSE %{buildroot}/usr/share/package-licenses/R-utf8/2b8b815229aa8a61e483fb4ba0588b8b6c491890 || :
cp %{_builddir}/utf8/src/utf8lite/LICENSE.Unicode %{buildroot}/usr/share/package-licenses/R-utf8/9425122e79ef5515a69d92efb3ec1b2e6acc62e3 || :
cp %{_builddir}/utf8/src/utf8lite/tests/wcwidth9/LICENSE %{buildroot}/usr/share/package-licenses/R-utf8/37e32619c63a0c3e9014a4c6f02b745bb4a54cc1 || :
LANG=C.UTF-8
CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS -O3 -flto -fno-semantic-interposition "
FCFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -flto -fno-semantic-interposition "
FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -flto -fno-semantic-interposition "
CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS -O3 -flto -fno-semantic-interposition "
AR=gcc-ar
RANLIB=gcc-ranlib
LDFLAGS="$CLEAR_INTERMEDIATE_LDFLAGS  -Wl,-z -Wl,relro"
mkdir -p %{buildroot}/usr/lib64/R/library

mkdir -p ~/.R
mkdir -p ~/.stash
echo "CFLAGS = $CFLAGS -march=x86-64-v3 -ftree-vectorize -mno-vzeroupper" > ~/.R/Makevars
echo "FFLAGS = $FFLAGS -march=x86-64-v3 -ftree-vectorize -mno-vzeroupper " >> ~/.R/Makevars
echo "CXXFLAGS = $CXXFLAGS -march=x86-64-v3 -ftree-vectorize -mno-vzeroupper " >> ~/.R/Makevars
R CMD INSTALL --install-tests --use-LTO --built-timestamp=${SOURCE_DATE_EPOCH} --data-compress=none --compress=none --build  -l %{buildroot}/usr/lib64/R/library .
for i in `find %{buildroot}/usr/lib64/R/ -name "*.so"`; do mv $i $i.avx2 ; mv $i.avx2 ~/.stash/; done
echo "CFLAGS = $CFLAGS -march=x86-64-v4 -ftree-vectorize  -mno-vzeroupper -mprefer-vector-width=512 " > ~/.R/Makevars
echo "FFLAGS = $FFLAGS -march=x86-64-v4 -ftree-vectorize  -mno-vzeroupper -mprefer-vector-width=512 " >> ~/.R/Makevars
echo "CXXFLAGS = $CXXFLAGS -march=x86-64-v4 -ftree-vectorize -mno-vzeroupper -mprefer-vector-width=512  " >> ~/.R/Makevars
R CMD INSTALL --preclean --install-tests --use-LTO --no-test-load --data-compress=none --compress=none --built-timestamp=${SOURCE_DATE_EPOCH} --build  -l %{buildroot}/usr/lib64/R/library .
for i in `find %{buildroot}/usr/lib64/R/ -name "*.so"`; do mv $i $i.avx512 ; mv $i.avx512 ~/.stash/; done
echo "CFLAGS = $CFLAGS -ftree-vectorize " > ~/.R/Makevars
echo "FFLAGS = $FFLAGS -ftree-vectorize " >> ~/.R/Makevars
echo "CXXFLAGS = $CXXFLAGS -ftree-vectorize " >> ~/.R/Makevars
R CMD INSTALL --preclean --use-LTO --install-tests --data-compress=none --compress=none --built-timestamp=${SOURCE_DATE_EPOCH} --build  -l %{buildroot}/usr/lib64/R/library .
cp ~/.stash/* %{buildroot}/usr/lib64/R/library/*/libs/ || :
%{__rm} -rf %{buildroot}%{_datadir}/R/library/R.css
%check
export LANG=C.UTF-8
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export _R_CHECK_FORCE_SUGGESTS_=false
R CMD check --no-manual --no-examples --no-codoc . || :

/usr/bin/elf-move.py avx2 %{buildroot}-v3 %{buildroot} %{buildroot}/usr/share/clear/filemap/filemap-%{name}

%files
%defattr(-,root,root,-)
/usr/lib64/R/library/utf8/DESCRIPTION
/usr/lib64/R/library/utf8/INDEX
/usr/lib64/R/library/utf8/LICENSE
/usr/lib64/R/library/utf8/Meta/Rd.rds
/usr/lib64/R/library/utf8/Meta/features.rds
/usr/lib64/R/library/utf8/Meta/hsearch.rds
/usr/lib64/R/library/utf8/Meta/links.rds
/usr/lib64/R/library/utf8/Meta/nsInfo.rds
/usr/lib64/R/library/utf8/Meta/package.rds
/usr/lib64/R/library/utf8/Meta/vignette.rds
/usr/lib64/R/library/utf8/NAMESPACE
/usr/lib64/R/library/utf8/R/utf8
/usr/lib64/R/library/utf8/R/utf8.rdb
/usr/lib64/R/library/utf8/R/utf8.rdx
/usr/lib64/R/library/utf8/doc/index.html
/usr/lib64/R/library/utf8/doc/utf8.Rmd
/usr/lib64/R/library/utf8/doc/utf8.html
/usr/lib64/R/library/utf8/help/AnIndex
/usr/lib64/R/library/utf8/help/aliases.rds
/usr/lib64/R/library/utf8/help/paths.rds
/usr/lib64/R/library/utf8/help/utf8.rdb
/usr/lib64/R/library/utf8/help/utf8.rdx
/usr/lib64/R/library/utf8/html/00Index.html
/usr/lib64/R/library/utf8/html/R.css
/usr/lib64/R/library/utf8/tests/testthat.R
/usr/lib64/R/library/utf8/tests/testthat/_snaps/ansi/utf8_format.md
/usr/lib64/R/library/utf8/tests/testthat/_snaps/unicode/utf8_format.md
/usr/lib64/R/library/utf8/tests/testthat/helper-capture_output.R
/usr/lib64/R/library/utf8/tests/testthat/helper-locale.R
/usr/lib64/R/library/utf8/tests/testthat/helper-options.R
/usr/lib64/R/library/utf8/tests/testthat/helper-output.R
/usr/lib64/R/library/utf8/tests/testthat/setup.R
/usr/lib64/R/library/utf8/tests/testthat/test-utf8_encode.R
/usr/lib64/R/library/utf8/tests/testthat/test-utf8_format.R
/usr/lib64/R/library/utf8/tests/testthat/test-utf8_normalize.R
/usr/lib64/R/library/utf8/tests/testthat/test-utf8_print.R
/usr/lib64/R/library/utf8/tests/testthat/test-utf8_valid.R
/usr/lib64/R/library/utf8/tests/testthat/test-utf8_width.R

%files lib
%defattr(-,root,root,-)
/usr/lib64/R/library/utf8/libs/utf8.so
/usr/lib64/R/library/utf8/libs/utf8.so.avx2
/usr/lib64/R/library/utf8/libs/utf8.so.avx512

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/R-utf8/2b8b815229aa8a61e483fb4ba0588b8b6c491890
/usr/share/package-licenses/R-utf8/37e32619c63a0c3e9014a4c6f02b745bb4a54cc1
/usr/share/package-licenses/R-utf8/9425122e79ef5515a69d92efb3ec1b2e6acc62e3
